// アイテム定義
// tools/convert.py により game_data_v26.xlsx から自動生成。直接編集しないこと。
const ITEMS_DATA = [
  {
    "id": "item_001",
    "name": "ニガタケ",
    "categoryId": "fungi",
    "effectId": "healing",
    "reactionId": "preserve",
    "description": "ありふれたキノコ。薬の材料になる。",
    "note": "基本素材 よく生えているキノコ。意外なことに薬になるが、味は良くない。火を加えると薬効が高まるが、味もひどく苦くなる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_002",
    "name": "ハシリタケ",
    "categoryId": "fungi",
    "effectId": "stimulation",
    "reactionId": "permeate",
    "description": "夜歩き出すという伝説のあるキノコ",
    "note": "一晩に数メートルから十数メートル移動するキノコ。いくつかの種類があるが、多量に摂取すると毒となる。少量なら興奮効果をもたらす。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_003",
    "name": "ニガハシリダケ",
    "categoryId": "fungi",
    "effectId": "stimulation",
    "reactionId": "volatile",
    "description": "ニガタケによく似ているが、現れては消えて夜の旅人の道行を惑わすという。",
    "note": "ニガタケによく似たハシリダケの一種。どこにでも見かけるキノコ、ニガタケに紛れて見つけにくい。ハシリダケの一種であるため、一晩に十メートル前後移動するが、じっと見つめていないとわからないため見つけにくい。キノコを目印にした旅人を惑わす。\n \n とれる場所：森 林\n \n 取れる時間帯：夜は確率が上がる。昼はニガタケにまじってまれに取れることがある。\n \n 調合のヒント：ニガタケとハシリタケの特性を持つが、鮮度が落ちるのが速い。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_004",
    "name": "ドロワリタケ",
    "categoryId": "fungi",
    "effectId": "tonic",
    "reactionId": "catalyst",
    "description": "沼地の泥炭層から生える黒くて平たいキノコ。水分を非常に多く含む。",
    "note": "泥の中ではその姿を捉えることは叶わないが、採取し洗ってみれば、泥炭の養分を凝縮したような漆黒の弾力が現れる。滋養強壮の薬として名高いが、真に驚くべきはその「触媒」としての力だ。このキノコを釜に投じれば、一夜で成長するその生命力が、本来は反応の遅い重い素材同士を強引に結びつけ、変化の時を早めてくれる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_005",
    "name": "ヌメリヒラタケ",
    "categoryId": "fungi",
    "effectId": "detox",
    "reactionId": "separate",
    "description": "腐った倒木に群生し、分解力が強い。",
    "note": "常に纏っている灰色の粘液は、倒木を分解し尽くす強欲な生命力の表れだ。この粘液は、調合において「分離」の力を発揮する。薬液に含まれる不要な濁りや、素材が持つ雑多な魔力をこの粘液が絡め取り、純粋な成分だけを鮮やかに切り離してくれる。化粧品に使われるのは、その清浄なまでの分解力ゆえだろう。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_006",
    "name": "ヤセボソシメジ",
    "categoryId": "fungi",
    "effectId": "healing",
    "reactionId": "catalyst",
    "description": "針葉樹の根元にひっそりと生える。見た目に反して旨味が強く、出汁によく出る。",
    "note": "針葉樹の影で今にも折れそうな姿をしているが、その身には驚くほどの「溶けやすさ」を秘めている。熱を加えた瞬間、形を失って薬液に溶け込み、周囲の素材の旨味と力を一つに束ね上げる。頑固で混ざり合わない素材同士を繋ぐその様子は、弱々しい見た目に反して、調合釜の中では誰よりも優れた「仲介役」となる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_007",
    "name": "ウロコモドキ",
    "categoryId": "fungi",
    "effectId": "sedation",
    "reactionId": "coagulate",
    "description": "傘の表面が魚の鱗のように硬質化したキノコ。すりつぶすと研磨剤のような粉になる。",
    "note": "傘の表面を覆う魚の鱗は、石のように硬く、並の刃では傷一つつかない。しかし、これを根気よくすりつぶして粉末にすれば、液体を瞬時に「凝固」させる強力な固め剤となる。滴るような薬液を、持ち運びやすい丸薬や固形へと変容させる際、このキノコの持つ「守りの硬さ」が役立つのだ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_008",
    "name": "カビツキヌメリ",
    "categoryId": "fungi",
    "effectId": "poison",
    "reactionId": "catalyst",
    "description": "他のキノコに寄生する白い菌。強い「発酵」を促す成分がある。",
    "note": "他の菌を侵食し、その性質を根底から書き換えてしまう寄生菌。採取した後は、この白い菌が持つ恐るべき「浸透」の力だけを利用する。一緒に入れた素材の核にある力を強制的に引き出し、ベースとなる水へと移し替えてしまう。その力は、まるで他の素材の魂を水へと溶かし出すかのようだ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_009",
    "name": "スナボコリタケ",
    "categoryId": "fungi",
    "effectId": "none",
    "reactionId": "volatile",
    "description": "乾燥した砂地に生える。衝撃を与えると細かい胞子（粉末）を噴き出す。",
    "note": "衝撃を与えれば最後、このキノコは一瞬で胞子の煙へと化す。この「揮発」しやすさは、調合においても最大の難所となる。熱を加えすぎれば、丹精込めた薬効もすべて煙となって消えてしまうだろう。薬の力を空気へと逃がさないよう、調合の最後にそっと加える繊細な手捌きが求められる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_010",
    "name": "ベニテングダマシ",
    "categoryId": "fungi",
    "effectId": "detox",
    "reactionId": "neutralize",
    "description": "毒キノコにそっくりだが毒はない。非常に苦く、「良薬口に苦し」を体現する。",
    "note": "猛毒のベニテングタケを模したその姿は、自らを守るための嘘に過ぎない。実際には毒などなく、ただただ閉口するほどに苦い。しかし、その「良薬口に苦し」を地で行く強烈な苦味は、他の素材が持つ尖った毒性を打ち消す「中和」の力を秘めている。偽物が本物を制する、奇妙な調和をもたらすキノコだ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_011",
    "name": "クサリフフダケ",
    "categoryId": "fungi",
    "effectId": "detox",
    "reactionId": "neutralize",
    "description": "腐肉の近くに生える独特の臭気を放つキノコ。解毒剤の反転素材として使われる。",
    "note": "腐肉の傍らでその臭気を吸って育つこのキノコは、死の際にある素材を好む。通常、毒を消すために使われる素材だが、その本質は「反転」にある。清浄な薬液をあえて腐敗の淵へと追い込み、極限の状態で見せる「毒をもって毒を制する」という危うい解毒の道行へ、調合者を誘う。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_012",
    "name": "ネバリイグチ",
    "categoryId": "fungi",
    "effectId": "none",
    "reactionId": "coagulate",
    "description": "松林の地中に埋まって生える。掘り起こすと強烈な粘り気があり、接合剤の役割を果たす。",
    "note": "地中に隠れたその身を掘り起こせば、糸を引くような強烈な粘り気が手につく。この粘りこそが、バラバラな成分を繋ぎ止める「凝固」の源泉だ。熱を加えてもその粘りは失われず、接合剤として薬を一つにまとめ上げ、完成した薬の形を永く保つための楔となる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_013",
    "name": "シロガネタケ",
    "categoryId": "fungi",
    "effectId": "insulation",
    "reactionId": "preserve",
    "description": "高山の岩肌にへばりつく白く乾いたキノコ。極寒に耐える性質（耐冷性）を持つ。",
    "note": "高山の凍てつく岩肌で、白く乾いたまま時を止めている。極寒に耐えうるその性質は、採取後も失われない。調合液にこのシロガネタケを加えれば、その「保存」の力が熱による劣化を防ぎ、薬の鮮度を雪の中に閉じ込めたかのように瑞々しく保ってくれる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_014",
    "name": "ホウオウノハネ",
    "categoryId": "fungi",
    "effectId": "stimulation",
    "reactionId": "catalyst",
    "description": "深紅と金色のグラデーションを持つ扇状のキノコ。煮出すと燃えるような熱を持つ。",
    "note": "煮出すと、まるで鳳凰の羽ばたきのように、釜の中に燃えるような熱が広がる。このキノコ自体が激しい変化を促す「触媒」であり、本来は決して混ざり合うことのない水と油、あるいは対立する属性の素材を、熱の奔流によって強引に融和させてしまう。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_015",
    "name": "ミズギワソウ",
    "categoryId": "flora",
    "effectId": "detox",
    "reactionId": "separate",
    "description": "川の合流地点にのみ自生する。茎がストロー状で、不純物を濾過する性質がある。",
    "note": "川の合流地点で、二つの異なる水流から魔力を選別して吸収している。ストロー状の茎は「不純な魔力」を濾過する天然のフィルターであり、調合液を通すことで、毒性や雑味だけを鮮やかに「分離」することができる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_016",
    "name": "イバラアザミ",
    "categoryId": "flora",
    "effectId": "healing",
    "reactionId": "permeate",
    "description": "鋭いトゲを持つ野草。傷をたちどころに治すという伝説がある。",
    "note": "鋭いトゲは魔を払う力を持つ。根に蓄えられた瑞々しい液は、生命力の奔流そのもの。切り口から滴る白い液は、傷口に触れると凝固して瞬時に傷を塞ぐ。内臓の傷をも癒やすという伝説は、止血効果によるもの。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_017",
    "name": "カサカサ草",
    "categoryId": "flora",
    "effectId": "none",
    "reactionId": "volatile",
    "description": "一年中枯れたような茶褐色の葉を持つ。油分を多く含み、火種（着火材）に最適。",
    "note": "乾ききった茶褐色の葉には、指で触れるだけで油がにじむ。この油こそが、調合における「揮発」の源泉だ。熱を加えた瞬間、葉は白い煙となって一息に気化し、混ぜ合わせた素材の成分を空気へと引き連れていく。気体薬や燻し薬を作る際の着火剤として、調合者たちが重宝する草だ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_018",
    "name": "オオツユグサ",
    "categoryId": "flora",
    "effectId": "sedation",
    "reactionId": "coagulate",
    "description": "早朝、葉の縁に大きな雫を溜める性質がある。水が貴重な場所での水源。",
    "note": "夜明け前、葉の縁にぷるりと膨らむ大粒の雫は、一日のうちで最も静謐な時間を閉じ込めている。この雫を集めて薬液に加えれば、昂った成分の動きを宥め、ゆっくりと「凝固」させる穏やかな力を発揮する。荒ぶる素材を落ち着かせ、一つの形にまとめる、夜明けの静けさを纏った草だ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_019",
    "name": "ニガヨモギモドキ",
    "categoryId": "flora",
    "effectId": "healing",
    "reactionId": "permeate",
    "description": "非常に香りが強く、虫除けに使われる。乾燥させて煎じると腹痛に効く。",
    "note": "その強烈な香気は、触れるものすべての奥深くへと染み入っていく。煎じれば腹の底まで温もりが「浸透」し、痛みの根を解きほぐす。虫すら寄せ付けぬその気を薬液に宿すことで、塗り薬や吸引薬の効果を皮の奥まで届ける媒介となる。刺激的な香りの裏に、静かで深い癒しの力を持つ草だ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_020",
    "name": "イワノボリツル",
    "categoryId": "flora",
    "effectId": "insulation",
    "reactionId": "coagulate",
    "description": "岩壁を這うように伸びる強靭なツル。繊維が丈夫で、煮出すと丈夫な紐になる。",
    "note": "岩の割れ目に爪を立てるようにして這い上がるその繊維は、引いても切れず、曲げても折れない。調合釜に投じれば、ばらばらに漂う成分を繊維で絡め取るように「凝固」させ、頑丈な薬の形を作り上げる。その丈夫さが体を守る「防護」の薬効へと転じ、傷口や患部を外の脅威から遮断する盾となる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_021",
    "name": "ツボミカズラ",
    "categoryId": "flora",
    "effectId": "tonic",
    "reactionId": "preserve",
    "description": "花が開かず、蕾のまま結実する珍しい植物。栄養が凝縮されている。",
    "note": "花開くことを拒み、すべての栄養を蕾の中に凝縮させたまま結実する蔓植物。その内に秘められた強烈な生命力は、調合において「保存 」の気質として現れる。完成した薬の中に、この蕾に閉じ込められた「時」を分け与えることで、薬効が腐敗するのを防ぎ、長きにわたってその力を維持させる 。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_022",
    "name": "ハッカガヤ",
    "categoryId": "flora",
    "effectId": "healing",
    "reactionId": "permeate",
    "description": "踏むと爽やかな香りが広がる草原の草。清涼感があり、熱を冷ます効果がある。",
    "note": "踏みしめるたびに清涼な香気が立ち上るこの草は、冷たさを肌の奥へと送り込む力を持つ。その香りを薬液に移せば、「浸透」の気質として表れ、熱を帯びた患部の深部まで癒しの冷気を届ける。熱病や炎症を和らげる薬において、効果を体の芯まで届ける道案内の役を担う。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_023",
    "name": "ネバリダイコン",
    "categoryId": "flora",
    "effectId": "tonic",
    "reactionId": "preserve",
    "description": "砂地に深く刺さった細長い根。水分を蓄える力が強く、保湿剤の原料になる。",
    "note": "砂漠の乾燥に抗い、砂の奥深くに水分を抱えたまま生き延びるこの根は、強靭な生命力の塊だ。調合液に加えれば、その「保存」の力が薬液全体に行き渡り、他の素材が揮発したり腐敗するのを防ぐ。同時に凝縮された滋養が「滋養強壮」として肉体の疲弊を回復させる、砂漠の恵みだ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_024",
    "name": "ミツユキソウ",
    "categoryId": "flora",
    "effectId": "mystic",
    "reactionId": "preserve",
    "description": "雪解けのわずかな期間にのみ姿を現す白い花。",
    "note": "雪解けの一瞬だけ顔を出し、また雪の下へと戻っていくこの花は、時間そのものを凝らせたような白さをしている。摘み取った瞬間から時が止まるかのようにその姿を保ち、調合液の中でも「保存」の力として働き、薬の劣化を長く拒む。その稀少な咲き方が宿す不思議な力は、魔力回路を一時的に開く「神秘」の薬効をもたらす。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_025",
    "name": "リュウノツノ",
    "categoryId": "flora",
    "effectId": "stable",
    "reactionId": "coagulate",
    "description": "砂漠の岩場に突き出た、ねじれた硬い枝。バラバラな成分を固める性質がある。",
    "note": "砂漠の過酷な乾燥に耐え、石のようにねじ曲がったその枝は、バラバラな属性を一つに束ねる「凝固」の力を象徴している。この硬い枝を砕いて投じれば、水に溶け出そうとする不安定な成分を物理的に絡め取り、一つの安定した霊薬へと形を成さしめる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_026",
    "name": "オロチノイバラ",
    "categoryId": "flora",
    "effectId": "poison",
    "reactionId": "separate",
    "description": "八方にうねるように伸びる猛毒の蔓。硬い素材を溶かして分解するという。",
    "note": "八方にのたうつ猛毒の蔓は、獲物を締め上げるのではなく「溶かして喰らう」ためのものだ。調合においても、その破壊的な「分離」の力は健在である。どんなに硬い鉱石であっても、この蔓と共に煮れば成分が解きほぐされ、必要な力だけを抽出することができる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_027",
    "name": "青泥石",
    "categoryId": "mineral",
    "effectId": "sedation",
    "reactionId": "preserve",
    "description": "底なし沼の深くから採れる、青みがかった粘土質の石。熱を逃がさない。",
    "note": "底なし沼の深みで、長い年月をかけて熱を溜め込んだ青みがかった粘土は、触れると不思議な温もりを持つ。この熱を手放さない性質が調合において「保存」の力として現れ、完成した薬の温かさと効能を逃がさず閉じ込める。また、その深く静かな粘土の重さは昂った気を沈め、「鎮静」の薬効として作用する。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_028",
    "name": "火打ち斑岩",
    "categoryId": "mineral",
    "effectId": "stimulation",
    "reactionId": "volatile",
    "description": "鉄分を多く含んだ黒い石。叩くと火花が出やすく、加工が難しい。",
    "note": "叩けば容赦なく火花を散らすこの黒い石は、そのままでは調合者の手を焦がす厄介者だ。しかし、この爆発的な反応こそが「揮発」の源泉となる。薬液に加えた瞬間、溶け出した鉄分が熱との触媒となり、成分を一気に気化させる。その烈しい弾けるような力が「興奮」の薬効として、摂取者の血を沸き立たせる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_029",
    "name": "白砂晶",
    "categoryId": "mineral",
    "effectId": "detox",
    "reactionId": "separate",
    "description": "砂漠の砂が固まってできた脆い結晶。水に溶けやすく、溶媒の性質を変える。",
    "note": "砂漠の砂が幾千年もかけて圧縮されたこの脆い結晶は、水に触れるや否や音もなく溶け消える。その溶けやすさは「分離」の力として現れ、薬液の中に潜む有害な成分だけを自ら引き受けて溶かし込み、無害な物質として流し去る。静かに消えていく様子は、毒を呑んで逝くようでもある。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_030",
    "name": "黄土塊",
    "categoryId": "mineral",
    "effectId": "tonic",
    "reactionId": "catalyst",
    "description": "栄養豊富な土壌が固まったもの。肥料の主原料や、土属性の触媒になる。",
    "note": "肥沃な大地の恵みが固まったこの塊は、土の記憶そのものだ。調合釜に投じれば、大地が草木を育てるように、周囲の素材の反応を活性化させる「触媒」として働く。豊富なミネラルと生命の養分は「滋養強壮」の薬効として肉体を内側から満たし、枯れかけた力を土が芽吹きを促すように引き出す。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_031",
    "name": "墨痕石",
    "categoryId": "mineral",
    "effectId": "detox",
    "reactionId": "separate",
    "description": "触ると手が黒くなる、炭に近い鉱石。不純物を吸着する性質がある。",
    "note": "触れた端から黒い汚れを残すこの石は、世界の汚れを自ら引き受ける性質を持つ。不純物を吸着し、透明な水へと変えるその「分離」の力は、毒を濾し取るための「解毒」工程において、他のどの素材よりも信頼のおけるフィルターとなるだろう。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_032",
    "name": "氷晶石モドキ",
    "categoryId": "mineral",
    "effectId": "sedation",
    "reactionId": "preserve",
    "description": "常にひんやりとしている、半透明の石。地下深くの冷気が溜まる場所に存在する。",
    "note": "地の底の凍った闇の中で、永い眠りにつくように時を過ごしてきた半透明の石。その芯に宿る冷気は採取後も失われず、薬液の温度を緩やかに下げ続ける。熱による劣化を防ぐ「保存」の力として、薬の鮮度を封じ込める。触れるだけで昂ぶりが静まるような冷たさは、「鎮静」の薬効として精神の熱を和らげる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_033",
    "name": "錆び鉄鉱",
    "categoryId": "mineral",
    "effectId": "stable",
    "reactionId": "catalyst",
    "description": "酸化が進んだ鉄の塊。煮出すと染料や特殊な反応剤になる。",
    "note": "長い年月をかけて酸化し、表面が深い赤褐色に染まったこの鉄の塊は、すでに変化を終えた素材だ。煮出せば澄んだ赤い汁が滲み出し、「触媒」として他の素材の反応を引き出す媒介となる。自身はもはや変化せず、周囲の成分を「安定」した反応へと導く、静かな存在だ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_034",
    "name": "雲母片岩",
    "categoryId": "mineral",
    "effectId": "insulation",
    "reactionId": "preserve",
    "description": "薄く剥がれやすい性質を持つ石。耐熱性が高く、調合釜のライナーに使われる。",
    "note": "爪の先でそっと触れれば、紙のように薄い層が次々と剥がれていく。しかしその一枚一枚は、調合釜の熱すら通さない頑強な盾だ。薬液に溶かせば、鎧のように他の成分を包み込んで「保存」し、外部の熱や湿気から守り抜く。飲み込んだ体の内側でも膜を張り、属性ダメージを遮断する「防護」として働く。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_035",
    "name": "潮石",
    "categoryId": "mineral",
    "effectId": "tonic",
    "reactionId": "permeate",
    "description": "昔、海だった場所が隆起してできた岩塩の一種。ミネラル分が極めて高い。",
    "note": "かつて海の底だったこの場所に積もった塩の記憶が、長い年月をかけて石となった。舐めれば古い海のすべての滋養が舌に広がり、その豊富なミネラルが「滋養強壮」の薬効として肉体の隅々まで染み渡る。水に溶かせば塩が自然と素材に食い込む「浸透」の力となり、他の薬効を体の深くへと届ける塩の道となる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_036",
    "name": "鈍色金",
    "categoryId": "mineral",
    "effectId": "stable",
    "reactionId": "coagulate",
    "description": "金属光沢はあるが、非常に重く加工しにくい未精製の鉱石。",
    "note": "鈍く重い光沢を放つこの鉱石は、採掘者の工具を次々と折り、精製を拒む頑固者だ。しかし砕いて粉末にし薬液に加えると、その重さが沈殿し他の浮遊する成分を引き寄せて「凝固」させる。ぶれることなく底に居座るその安定感は、薬全体の成分を落ち着かせる「安定」の薬効として、不安定な調合を地に足のついたものへと変える。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_037",
    "name": "キリンノナミダ",
    "categoryId": "mineral",
    "effectId": "detox",
    "reactionId": "neutralize",
    "description": "虹色の光沢を持つ珍しい樹脂の化石。毒性を打ち消す浄化の性質を持つ。",
    "note": "伝説の獣が流した涙が固まったという、虹色の化石。その輝きは、万物の毒性を浄化する至高の「中和」の力を宿している。どれほど危険な素材を組み合わせたとしても、この石を最後に一粒加えるだけで、禍々しい反応は凪ぎ、清らかな聖薬へと生まれ変わる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_038",
    "name": "鍾乳洞の滴り",
    "categoryId": "liquid",
    "effectId": "none",
    "reactionId": "coagulate",
    "description": "岩の滴りが集まった水。バラバラな素材を一つに結び安定させる「凝固」の気質を持つ。",
    "note": "岩の隙間を幾年もかけて滲み落ちてきた滴は、石の記憶をすべて溶かし込んでいる。この水が薬液に加わると、浮遊する粒子をゆっくりと引き寄せ、ひとつに「凝固」させる。荒ぶる成分を宥め、静かに形を固める。石が時間をかけて鍾乳石を作るように、この水は薬に揺るぎない輪郭を与える。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_039",
    "name": "雨溜まりの泥水",
    "categoryId": "liquid",
    "effectId": "none",
    "reactionId": "catalyst",
    "description": "地上の雑多な気が混じった水。素材をわざと腐らせたり発酵を早めたりする際に用いられる。",
    "note": "地面に落ちた雨が、土の臭い、草の腐れ、虫の残り香を吸い込んで溜まった水だ。清浄とはほど遠いが、それこそがこの水の本領である。調合釜に加えれば、どんな素材をも緩やかな腐敗へと引き込み、発酵を促す触媒となる。毒も薬も紙一重。この水が腐らせる力こそが、変質の入口だ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_040",
    "name": "草木の朝露",
    "categoryId": "liquid",
    "effectId": "none",
    "reactionId": "permeate",
    "description": "天から降り汚れを知らない清らかな水。草木の繊細な薬効をそのまま吸い出す力を持つ。",
    "note": "夜明け前、草木の葉が天の清気を受けて結んだ露。一粒として濁りを知らぬその水は、素材が持つ本来の力を丸ごと「浸透」させて吸い出す。添加物も雑味も混じらず、ただ純粋に薬効だけを引き出す。繊細な花弁や希少な根から力を損なわず引き出したいとき、調合者がまず手に取る水だ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_041",
    "name": "鉄渋の湧き水",
    "categoryId": "liquid",
    "effectId": "tonic",
    "reactionId": "preserve",
    "description": "大地の血が混じったような重く渋い水。色や効能を素材に深く刻み込み定着させる性質がある。",
    "note": "大地の鉄分が血のように溶け込んだ重く渋い水。口に含めば、舌に鈍い鉄の味が長く残る。この定着力こそが調合における「保存」の源だ。薬液に加えれば、素材が持つ色と効能を深く刻み込み、完成した薬の力が容易に褪せないよう大地の重さで封じ込める。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_042",
    "name": "雪解けの走り水",
    "categoryId": "liquid",
    "effectId": "stimulation",
    "reactionId": "catalyst",
    "description": "冬の眠りから覚めたばかりの勢いのある水。乾燥して眠った素材に一時的な活力を吹き込む。",
    "note": "雪が解けて地表を走り始めたばかりの水は、冬の眠りを破った勢いをそのまま宿している。乾燥して力を失いかけた素材に加えれば、その奔流が眠った成分を目覚めさせ、反応をわずかに活性化させる。長くは続かない一時の高揚だが、調合の起点を作る呼び水として侮れない。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_043",
    "name": "古井戸の溜まり水",
    "categoryId": "liquid",
    "effectId": "none",
    "reactionId": "preserve",
    "description": "光を拒み静寂を湛えた深い水。調合した薬が変質しないようその瞬間の効能を封じ込める。",
    "note": "光も届かず、音すら吸い込む古い井戸の底に溜まった水。何も変えず、何も動かさず、ただ静かに在り続けてきた。その静寂が調合における「保存」の力となる。薬液に一滴加えるだけで、時の流れそのものを緩やかにするかのように、完成した薬の効能を長くその瞬間のまま封じ込める。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_044",
    "name": "灰から取った灰汁",
    "categoryId": "liquid",
    "effectId": "none",
    "reactionId": "permeate",
    "description": "火の残滓（灰）を通した水。頑固な皮や硬い根の結びつきを解き柔らかく解きほぐす。",
    "note": "灰を通して濾された強アルカリの水は、触れるものの結びつきを緩め、硬い皮も頑固な根も柔らかく解きほぐす。この「浸透」の力が調合において真価を発揮する。本来は素材の奥深くへ届かない他の成分を、この灰汁が道を切り拓き、奥底まで染み渡らせる。火の残滓が生む、静かな解放の水だ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_045",
    "name": "地熱帯の硫黄水",
    "categoryId": "liquid",
    "effectId": "insulation",
    "reactionId": "volatile",
    "description": "大地の熱を孕んで湧き出す鼻を突く水。火を止めた後も薬の中に温かな熱を留め続ける。",
    "note": "硫黄の臭いとともに大地の熱を帯びて湧き出すこの水は、火を止めた後も釜の中に温もりを宿し続ける。その持続する熱が調合において固有の働きをする。他の素材が揮発しないよう抑えながら、薬液全体に均一な熱を長く保ち、仕上がりに芯からの温かさを与える。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_046",
    "name": "樹皮を伝う雨水",
    "categoryId": "liquid",
    "effectId": "none",
    "reactionId": "coagulate",
    "description": "森の吐息を吸い込んだわずかに粘りある水。本来混じり合わない粉末同士を繋ぎ合わせる。",
    "note": "雨が木の幹を伝い落ちる間に、樹皮の樹脂と苔の湿気を吸い込んだわずかに粘りある水。その粘性が「凝固」の源となる。本来は互いを弾く粉末同士を包み込むように繋ぎ合わせ、ひとつの薬の形へとまとめ上げる。森が雨を受け止めるように、この水は成分を静かに抱きまとめる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_047",
    "name": "深層の塩水",
    "categoryId": "liquid",
    "effectId": "tonic",
    "reactionId": "separate",
    "description": "遥か古の海が地底に閉じ込められたもの。素材の奥底に眠る成分を表へと引きずり出す。",
    "note": "太古の海が地殻変動で閉じ込められ、濃縮され続けた塩水。その高い塩分濃度が浸透圧として働き、素材の奥底に眠る成分を強引に表面へと引きずり出す。どれほど不溶性の成分でも、この古い海の引力には抗えない。必要な力だけを抽出したいとき、深層の塩水は最も頼れる「分離」の器だ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_048",
    "name": "カミソリウオの鱗",
    "categoryId": "creature",
    "effectId": "stimulation",
    "reactionId": "catalyst",
    "description": "カミソリのように鋭いエラを持つ小魚の鱗。劇薬の触媒に使われる。",
    "note": "カミソリのように薄く鋭い鱗は、指先をわずかに触れただけでも切れる。その切れ味が調合において「触媒」の力として現れる。他の成分が互いを傷つけることなく反応するよう、この鱗が境界を整え、混ざり合いを促進する。刃が素材を切り分けるように、この鱗は反応の障壁を断ち切る。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_049",
    "name": "トゲネズミの抜け殻",
    "categoryId": "creature",
    "effectId": "stimulation",
    "reactionId": "permeate",
    "description": "興奮すると針を飛ばすネズミの皮。目覚め薬や気付け薬の調合に使われる。",
    "note": "興奮が頂点に達すると全身の針を弾き飛ばすというネズミの、その張り詰めた抜け殻。一触即発の緊張感は採取後も宿っており、調合液に加えると成分を「興奮」状態へと引き込む。使う側が感じる一時的な高揚と覚醒は、この皮が最後まで手放さなかった野生の張力から来るものだ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_050",
    "name": "ミズススリの浮き袋",
    "categoryId": "creature",
    "effectId": "levitation",
    "reactionId": "volatile",
    "description": "水面を滑るように走る虫の器官。非常に軽く、「風」の気質を付与する。",
    "note": "水の上を走る虫が浮力を保つためだけに持つこの器官は、空気よりも軽い何かを内包している。調合に加えると、成分が液体から気体へと移行する「揮発」を著しく加速させる。気体薬や霧吹き薬を作るとき、この浮き袋の軽さが成分を空中へと解き放つ、見えない翼となる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_051",
    "name": "粘りツチガエルの粘液",
    "categoryId": "creature",
    "effectId": "healing",
    "reactionId": "preserve",
    "description": "触れると糸を引くほど粘るカエルの分泌物。揮発しやすい成分を「留める」定着剤。",
    "note": "採取した指の間で糸を引くほどの粘りは、乾かそうとしても乾かず、熱を加えても流れない。この執拗な粘りが調合における「保存」の要となる。揮発しやすい成分をこの粘液が絡め取り、薬の形が崩れないよう長く留め続ける。飛び去ろうとする力を、泥のような粘りが静かに引き止める。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_052",
    "name": "ハバタキ蛾の粉末",
    "categoryId": "creature",
    "effectId": "levitation",
    "reactionId": "catalyst",
    "description": "夜に高速で羽ばたく蛾の羽の粉。摩擦熱を呼びやすく、「火」属性の熱を増幅させる。",
    "note": "夜ごと高速で羽ばたき続ける蛾の羽が削れ、摩擦で帯電した粉末。指で触れると微かな熱を感じる。この摩擦熱を呼ぶ性質が「触媒」として機能し、調合において他の素材の反応を底から熱し、変化を急かす。暗闇の中で炎を求めるように、この粉末は化学反応の炎に油を注ぐ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_053",
    "name": "ガンセキガメの甲羅破片",
    "categoryId": "creature",
    "effectId": "insulation",
    "reactionId": "separate",
    "description": "岩に擬態するほど硬い亀の甲羅。磨り潰すと液体の沈殿を早める効果がある。",
    "note": "岩そのものにしか見えない甲羅の破片は、磨り潰すと比重の重い微細な粉となる。この粉が薬液に加わると、沈殿を早める錨のように働き、不純な成分を速やかに底へと引き落として「分離」させる。上澄みだけを取り出す工程において、この亀の硬さは最も誠実な助手だ。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_054",
    "name": "ツギハギヘビの抜け殻",
    "categoryId": "creature",
    "effectId": "none",
    "reactionId": "coagulate",
    "description": "場所によって模様がバラバラな蛇。素材同士の相性を無理やり「繋ぐ」潤滑剤。",
    "note": "生まれた環境ごとに色が変わるという蛇が脱いだ抜け殻は、継ぎ接ぎのように模様がバラバラだ。しかし、その不均一さが調合の「凝固」において独自の力を発揮する。本来は反発し合う素材同士を、この皮の継ぎ接ぎの柔軟さが無理やり繋ぎ止め、ひとつの形に押し込める潤滑剤となる。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_055",
    "name": "ホタルコウモリの牙",
    "categoryId": "creature",
    "effectId": "mystic",
    "reactionId": "catalyst",
    "description": "微かに光る超音波を出すコウモリの牙。神経を研ぎ澄ます薬に使う。",
    "note": "夜空を飛びながら超音波を放ち、世界の輪郭を音で描くコウモリの牙。微かに発光するその牙は、採取後も光を宿している。調合に加えると、見えない周波数が薬液に波紋を広げるように「神秘」の薬効として現れ、摂取者の神経を研ぎ澄まし、普段は届かぬ感覚の領域へと扉を開く。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_056",
    "name": "ケムリイタチの毛束",
    "categoryId": "creature",
    "effectId": "none",
    "reactionId": "preserve",
    "description": "怒ると体から煙を吹くイタチの毛。「蒸す」工程の効果を長く保つ性質がある。",
    "note": "怒りが頂点に達すると体中から白い煙を噴き出すイタチの毛は、熱を蓄える特殊な構造を持つ。「蒸す」工程でこの毛束を加えると、生じた蒸気が素材に深く浸透した後も長く留まり続ける「保存」の効果をもたらす。怒りの白煙が晴れた後に残るように、この毛の熱は薬の中に静かに宿り続ける。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_057",
    "name": "オオミミウサギの乾き耳",
    "categoryId": "creature",
    "effectId": "mystic",
    "reactionId": "permeate",
    "description": "音に敏感すぎるウサギの耳を乾燥させたもの。感覚を鋭敏にする調合に。",
    "note": "あらゆる音を聞き取りすぎるゆえに正気を保てず、最終的には自ら耳を地面に押しつけて死ぬという伝説を持つウサギの耳。乾燥させるとその過敏さが凝縮される。調合に加えると、摂取者の感覚をわずかな刺激にも応じるほど鋭敏にする「神秘」の薬効として現れる。世界の微細な囁きが、突然届き始めるだろう。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_058",
    "name": "サボテンドラゴンの鱗",
    "categoryId": "creature",
    "effectId": "insulation",
    "reactionId": "preserve",
    "description": "サボテンのトゲをバリバリ食べる大型トカゲの鱗。乾燥工程での変質を防ぐ。",
    "note": "サボテンのトゲを噛み砕き、砂漠の熱気の中を平然と歩くトカゲの鱗は、極端な乾燥に晒されても変質しない。この耐乾性が調合において「保存」として働き、乾燥工程で素材が劣化したり収縮するのを防ぐ。過酷な環境でも姿を変えないこのトカゲのように、薬の品質をそのまま守り抜く。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_059",
    "name": "蒸留水",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "separate",
    "description": "水質素材を蒸留して得た、不純物のない水。あらゆる調合の基準となる溶媒。",
    "note": "中間素材。ほぼ全ての上位調合の土台になる。まずこれを安定して作れるようになることが第一歩。",
    "source": "調合",
    "price": 25,
    "use": "素材",
    "shopUnlock": 100,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_060",
    "name": "純化水",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "separate",
    "description": "蒸留水からさらに雑味を切り離した水。薬効の輪郭がはっきりする。",
    "note": "中間素材。分離特性の素材を溶かし込むことで、蒸留では取り切れない濁りが沈む。",
    "source": "調合",
    "price": 60,
    "use": "素材",
    "shopUnlock": 50,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_061",
    "name": "超純水",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "catalyst",
    "description": "二重の浄化を経た究極の水。何も含まないがゆえに、あらゆる力をよく受け入れる。",
    "note": "中間素材（上位）。秘薬級の調合はほぼ全てこれを土台とする。作るのに手間がかかる。",
    "source": "調合",
    "price": 140,
    "use": "素材",
    "shopUnlock": 20,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_062",
    "name": "凝固薬",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "coagulate",
    "description": "液体を固形へと変える基本の固め剤。丸薬や膏薬の土台になる。",
    "note": "中間素材。持ち運べる形の薬を作るなら必ず要る。",
    "source": "調合",
    "price": 40,
    "use": "素材",
    "shopUnlock": 50,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_063",
    "name": "浸透溶媒",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "permeate",
    "description": "成分を身体の深くまで運ぶ溶媒。効き目の速さを決める。",
    "note": "中間素材。同じ薬効でもこれを使うと効きが早い。",
    "source": "調合",
    "price": 45,
    "use": "素材",
    "shopUnlock": 50,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_064",
    "name": "強発酵液",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "catalyst",
    "description": "泥水と菌類から生まれた濁った液。旺盛な発酵力を持つ。",
    "note": "中間素材。酒精づくりの起点。匂いは強烈だが力は本物。",
    "source": "調合",
    "price": 35,
    "use": "素材",
    "shopUnlock": 50,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_065",
    "name": "保存溶液",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "preserve",
    "description": "素材の鮮度を長く保つ液。遠征前の仕込みに欠かせない。",
    "note": "中間素材。鮮度の落ちやすい素材を扱うなら先に用意しておきたい。",
    "source": "調合",
    "price": 40,
    "use": "素材",
    "shopUnlock": 50,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_066",
    "name": "促進触媒",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "catalyst",
    "description": "反応の遅い素材同士を強引に結びつける、調合師の切り札。",
    "note": "中間素材（上位）。これがあると本来成立しない組み合わせが成立する。",
    "source": "調合",
    "price": 150,
    "use": "素材",
    "shopUnlock": 20,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_067",
    "name": "冷却晶",
    "categoryId": "processed",
    "effectId": "sedation",
    "reactionId": "preserve",
    "description": "氷晶石モドキに水を纏わせ結晶化させたもの。融けずに冷気を保ち続ける。",
    "note": "中間素材。熱を扱う調合の相方。そのまま懐に入れても冷たい。",
    "source": "調合",
    "price": 70,
    "use": "素材",
    "shopUnlock": 50,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_068",
    "name": "木灰",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "separate",
    "description": "植物を焼いて得た灰。灰汁の原料であり、脂を分ける力を持つ。",
    "note": "中間素材。最も安く手に入る加工品。侮れない使い道が多い。",
    "source": "調合",
    "price": 10,
    "use": "素材",
    "shopUnlock": 100,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_069",
    "name": "鉱石粉",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "coagulate",
    "description": "鉱物を挽いた細かな粉。粉薬の担体や研磨に使う。",
    "note": "中間素材。それ自体に薬効はないが、粉薬の「かさ」として要る。",
    "source": "調合",
    "price": 12,
    "use": "素材",
    "shopUnlock": 100,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_070",
    "name": "薬草粉",
    "categoryId": "processed",
    "effectId": "healing",
    "reactionId": "permeate",
    "description": "治癒の草を乾かして挽いた粉。傷にも飲用にも使える万能の基剤。",
    "note": "中間素材。乾燥させてから挽くのが要点。生のまま挽くと効き目が落ちる。",
    "source": "調合",
    "price": 30,
    "use": "素材",
    "shopUnlock": 100,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_071",
    "name": "骨炭",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "separate",
    "description": "獣の骨や殻を焼いた黒い炭。色と臭いを吸い取る。",
    "note": "中間素材。毒や臭みを抜く工程で使う。",
    "source": "調合",
    "price": 18,
    "use": "素材",
    "shopUnlock": 100,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_072",
    "name": "精製塩",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "preserve",
    "description": "深層の塩水を干して得た白い結晶。保存の要。",
    "note": "中間素材。塩水を煮るのではなく干すこと。煮ると苦味が残る。",
    "source": "調合",
    "price": 20,
    "use": "素材",
    "shopUnlock": 100,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_073",
    "name": "硫黄華",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "volatile",
    "description": "硫黄水を蒸留して得た黄色い粉。燃やすと刺激臭のある煙になる。",
    "note": "中間素材。虫除けと耐火の両方に使える。扱いには換気を。",
    "source": "調合",
    "price": 45,
    "use": "素材",
    "shopUnlock": 50,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_074",
    "name": "鉄粉",
    "categoryId": "processed",
    "effectId": "stable",
    "reactionId": "catalyst",
    "description": "錆び鉄鉱を挽いた粉。薬に重さと安定をもたらす。",
    "note": "中間素材。効き目を長持ちさせたい時に少量混ぜる。",
    "source": "調合",
    "price": 25,
    "use": "素材",
    "shopUnlock": 100,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_075",
    "name": "麹",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "catalyst",
    "description": "菌類を寝かせて育てた発酵の種。酒精づくりの起点。",
    "note": "中間素材。菌類なら何でも種になるが、種類で仕上がりの癖が変わるらしい。",
    "source": "調合",
    "price": 22,
    "use": "素材",
    "shopUnlock": 100,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_076",
    "name": "灰汁液",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "separate",
    "description": "木灰を煮出した強いアルカリ液。脂を溶かし、汚れを断つ。",
    "note": "中間素材。素手で触らないこと。",
    "source": "調合",
    "price": 25,
    "use": "素材",
    "shopUnlock": 100,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_077",
    "name": "獣脂",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "preserve",
    "description": "獣から煮出した脂。軟膏や石鹸の基材となる。",
    "note": "中間素材。塗り薬を作るならこれが土台。",
    "source": "調合",
    "price": 35,
    "use": "素材",
    "shopUnlock": 50,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_078",
    "name": "膠",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "coagulate",
    "description": "抜け殻を煮詰めて作る接着材。乾けば強く固まる。",
    "note": "中間素材。凝固薬より強く、しかし熱に弱い。",
    "source": "調合",
    "price": 50,
    "use": "素材",
    "shopUnlock": 50,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_079",
    "name": "香油",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "permeate",
    "description": "獣脂に花草の香りを移した油。肌によく馴染む。",
    "note": "中間素材。香りの薬はここから枝分かれする。",
    "source": "調合",
    "price": 75,
    "use": "素材",
    "shopUnlock": 50,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_080",
    "name": "解毒エキス",
    "categoryId": "processed",
    "effectId": "detox",
    "reactionId": "permeate",
    "description": "解毒素材を煮出し濃縮した液。ほとんどの毒に一定の効き目がある。",
    "note": "中間素材。応急処置ならこれで足りる。強い毒には上位品が要る。",
    "source": "調合",
    "price": 90,
    "use": "素材",
    "shopUnlock": 20,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_081",
    "name": "猛毒エキス",
    "categoryId": "processed",
    "effectId": "poison",
    "reactionId": "permeate",
    "description": "毒草を溶かし込んだ透明な液。無臭であることが何より恐ろしい。",
    "note": "中間素材。扱いは自己責任で。純化水で溶くと痕跡が残らない。",
    "source": "調合",
    "price": 130,
    "use": "素材",
    "shopUnlock": 20,
    "form": "液体",
    "danger": "要注意"
  },
  {
    "id": "item_082",
    "name": "霊銀砂",
    "categoryId": "processed",
    "effectId": "mystic",
    "reactionId": "catalyst",
    "description": "神秘の素材を挽き、鉱石粉と混ぜた銀色の砂。魔力をよく通す。",
    "note": "中間素材（上位）。秘薬級の調合には大抵これが要る。",
    "source": "調合",
    "price": 180,
    "use": "素材",
    "shopUnlock": 10,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_083",
    "name": "酒精",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "volatile",
    "description": "発酵液を蒸留して得た強い酒。薬を溶かし、傷を清める。",
    "note": "中間素材。飲むためのものではない、ということになっている。",
    "source": "調合",
    "price": 80,
    "use": "素材",
    "shopUnlock": 50,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_084",
    "name": "硬化油",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "coagulate",
    "description": "香油を凝固薬で固めた半固形の油。塗った場所に留まり続ける。",
    "note": "中間素材。流れ落ちては困る薬に使う。",
    "source": "調合",
    "price": 95,
    "use": "素材",
    "shopUnlock": 20,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_085",
    "name": "苦灰塩",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "neutralize",
    "description": "木灰と塩を練り合わせた灰白色の粉。酸と毒を穏やかに打ち消す。",
    "note": "中間素材。中和素材が手元にない時の代用にもなる。",
    "source": "調合",
    "price": 35,
    "use": "素材",
    "shopUnlock": 50,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_086",
    "name": "鎮静水",
    "categoryId": "processed",
    "effectId": "sedation",
    "reactionId": "permeate",
    "description": "鎮静素材を蒸留水で煮出した澄んだ液。眠りの薬の土台。",
    "note": "中間素材。濃くしすぎると目覚めなくなる。",
    "source": "調合",
    "price": 60,
    "use": "素材",
    "shopUnlock": 50,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_087",
    "name": "活性水",
    "categoryId": "processed",
    "effectId": "stimulation",
    "reactionId": "permeate",
    "description": "興奮素材を蒸留水で煮出した液。飲むと指先まで熱くなる。",
    "note": "中間素材。連用は勧められない。",
    "source": "調合",
    "price": 60,
    "use": "素材",
    "shopUnlock": 50,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_088",
    "name": "気体瓶",
    "categoryId": "relics",
    "effectId": "none",
    "reactionId": "preserve",
    "description": "気体を封じるための口の狭い瓶。行商人が束で売っている。",
    "note": "購入品。気体の調合品を作るときに自動で使われる。瓶がなければ、生じた気体はその場で散ってしまう。中身を材料として使えば、瓶は棚に戻る。",
    "source": "購入",
    "price": 30,
    "use": "素材",
    "shopUnlock": 0,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_089",
    "name": "錆びた釘",
    "categoryId": "relics",
    "effectId": "stable",
    "reactionId": "catalyst",
    "description": "遺跡の梁から抜き取った鉄の釘。赤錆を纏っている。",
    "note": "購入品。錆びているほど良いとされる。鉄気が薬を落ち着かせるらしい。",
    "source": "採取",
    "price": 15,
    "use": "素材",
    "shopUnlock": 150,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_090",
    "name": "古銭",
    "categoryId": "relics",
    "effectId": "insulation",
    "reactionId": "preserve",
    "description": "誰も使わなくなった時代の銅貨。表面に緑青が浮いている。",
    "note": "購入品。緑青には物を腐らせない力がある。傷薬に触れさせると日持ちが変わる。",
    "source": "採取",
    "price": 25,
    "use": "素材",
    "shopUnlock": 100,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_091",
    "name": "陶片",
    "categoryId": "relics",
    "effectId": "none",
    "reactionId": "coagulate",
    "description": "割れた壺のかけら。素焼きのため水をよく吸う。",
    "note": "購入品。安い。粉を練るときの受け皿にも、素材そのものにもなる。",
    "source": "採取",
    "price": 10,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_092",
    "name": "鉛の錘",
    "categoryId": "relics",
    "effectId": "poison",
    "reactionId": "preserve",
    "description": "漁網に使われていた柔らかい金属の塊。ずしりと重い。",
    "note": "購入品。扱った手で物を食べてはいけない。じわじわと人を弱らせる金属だ。",
    "source": "採取",
    "price": 35,
    "use": "素材",
    "shopUnlock": 100,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_093",
    "name": "鏡の破片",
    "categoryId": "relics",
    "effectId": "mystic",
    "reactionId": "separate",
    "description": "磨かれた金属鏡のかけら。曇っているのに、時折こちらを覗き返す。",
    "note": "購入品。高価。映すという行為そのものに力が宿ると考える者もいる。",
    "source": "採取",
    "price": 120,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_094",
    "name": "銅線",
    "categoryId": "relics",
    "effectId": "none",
    "reactionId": "catalyst",
    "description": "何かの装置から解かれた細い銅の線。艶がある。",
    "note": "購入品。熱と力をよく通す。反応を全体に行き渡らせたい時に。",
    "source": "採取",
    "price": 20,
    "use": "素材",
    "shopUnlock": 150,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_095",
    "name": "香炉の欠片",
    "categoryId": "relics",
    "effectId": "sedation",
    "reactionId": "volatile",
    "description": "神殿で使われていた香炉のかけら。今も甘い匂いが染みついている。",
    "note": "購入品。染み込んだ香が抜けきらない。焚けば当時の匂いが立ち上る。",
    "source": "採取",
    "price": 60,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_096",
    "name": "硫黄の気",
    "categoryId": "processed",
    "effectId": "insulation",
    "reactionId": "volatile",
    "description": "瓶の中で黄色く揺れる気体。栓を抜くと刺すような臭いが広がる。",
    "note": "調合品。虫も獣も逃げ出す。密閉したまま持ち歩くこと。",
    "source": "調合",
    "price": 110,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "気体",
    "danger": "無害"
  },
  {
    "id": "item_097",
    "name": "眠りの気",
    "categoryId": "processed",
    "effectId": "sedation",
    "reactionId": "volatile",
    "description": "無色の気体。瓶越しに見ると、わずかに景色が歪む。",
    "note": "調合品。吸えば数分で膝から力が抜ける。自分が吸わないように。",
    "source": "調合",
    "price": 140,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "気体",
    "danger": "要注意"
  },
  {
    "id": "item_098",
    "name": "灯りの気",
    "categoryId": "processed",
    "effectId": "mystic",
    "reactionId": "volatile",
    "description": "瓶の中でぼんやりと青白く光り続ける気体。熱はない。",
    "note": "調合品。燃えないのに光る。灯守の間では蝋燭より重宝される。",
    "source": "調合",
    "price": 190,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "気体",
    "danger": "無害"
  },
  {
    "id": "item_099",
    "name": "毒の気",
    "categoryId": "processed",
    "effectId": "poison",
    "reactionId": "volatile",
    "description": "わずかに緑がかった気体。瓶の内側に細かな滴が付く。",
    "note": "調合品。取り扱いは自己責任で。栓の蝋は二重に。",
    "source": "調合",
    "price": 210,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "気体",
    "danger": "凶器"
  },
  {
    "id": "item_100",
    "name": "清めの気",
    "categoryId": "processed",
    "effectId": "detox",
    "reactionId": "volatile",
    "description": "つんとした匂いの透明な気体。空気そのものを洗うという。",
    "note": "調合品。病の流行った家に一瓶。窓を閉めて焚く。",
    "source": "調合",
    "price": 130,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "気体",
    "danger": "無害"
  },
  {
    "id": "item_101",
    "name": "加速の秘薬",
    "categoryId": "processed",
    "effectId": "stimulation",
    "reactionId": "volatile",
    "description": "飲むと足取りが軽くなる秘薬。僅かに苦い後味が残る。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 30,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_102",
    "name": "汎用毒消し",
    "categoryId": "processed",
    "effectId": "detox",
    "reactionId": "neutralize",
    "description": "ありふれた毒なら大抵これで足りる、基本の毒消し。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 30,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_103",
    "name": "野草の傷薬",
    "categoryId": "processed",
    "effectId": "healing",
    "reactionId": "permeate",
    "description": "そのへんの草で作れる素朴な傷薬。旅の常備品。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 30,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_104",
    "name": "鎮静の丸薬",
    "categoryId": "processed",
    "effectId": "sedation",
    "reactionId": "coagulate",
    "description": "気を静める丸薬。噛まずに飲み下すこと。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 45,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_105",
    "name": "目覚め薬",
    "categoryId": "processed",
    "effectId": "stimulation",
    "reactionId": "volatile",
    "description": "鼻に近づけるだけで眠気が飛ぶ刺激薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 30,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_106",
    "name": "滋養の煎じ薬",
    "categoryId": "processed",
    "effectId": "tonic",
    "reactionId": "permeate",
    "description": "疲れた体に染み渡る煎じ薬。鉄の味がする。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 45,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_107",
    "name": "煙の護符",
    "categoryId": "processed",
    "effectId": "insulation",
    "reactionId": "volatile",
    "description": "焚くと薄い煙の膜を張り、身を守る護符。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 45,
    "use": "道具",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_108",
    "name": "万能解毒剤",
    "categoryId": "processed",
    "effectId": "detox",
    "reactionId": "neutralize",
    "description": "強い毒にも届く上等な解毒剤。値は張る。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 430,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_109",
    "name": "上質な傷薬",
    "categoryId": "processed",
    "effectId": "healing",
    "reactionId": "permeate",
    "description": "純化水で仕立てた澄んだ傷薬。跡が残りにくい。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 120,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_110",
    "name": "巫女セレネの霊視香",
    "categoryId": "processed",
    "effectId": "mystic",
    "reactionId": "volatile",
    "description": "焚けば見えざるものの輪郭が浮かぶという神殿の香。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 80,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_111",
    "name": "蛇牙の塗り毒",
    "categoryId": "processed",
    "effectId": "poison",
    "reactionId": "coagulate",
    "description": "刃に塗って使う粘つく毒。扱いは慎重に。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 30,
    "use": "道具",
    "shopUnlock": null,
    "form": "固形",
    "danger": "凶器"
  },
  {
    "id": "item_112",
    "name": "硬化の膏薬",
    "categoryId": "processed",
    "effectId": "stable",
    "reactionId": "coagulate",
    "description": "塗ると皮膚が硬く締まる膏薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 85,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_113",
    "name": "灯守ヨナの常夜灯",
    "categoryId": "processed",
    "effectId": "mystic",
    "reactionId": "preserve",
    "description": "燃料のいらない灯り。灯守の一族が守り伝えた。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 310,
    "use": "道具",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_114",
    "name": "獣香の誘引剤",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "permeate",
    "description": "獣を引き寄せる強烈な匂いの液。風上で使うこと。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 30,
    "use": "道具",
    "shopUnlock": null,
    "form": "液体",
    "danger": "要注意"
  },
  {
    "id": "item_115",
    "name": "眠り姫マルグレーテの微睡み香",
    "categoryId": "processed",
    "effectId": "sedation",
    "reactionId": "volatile",
    "description": "百年の眠りを招いたと伝わる香。分量を誤らぬこと。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 655,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "要注意"
  },
  {
    "id": "item_116",
    "name": "鉄壁の護り薬",
    "categoryId": "processed",
    "effectId": "insulation",
    "reactionId": "coagulate",
    "description": "塗った箇所に硬い皮膜を張る護りの薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 85,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_117",
    "name": "消臭の中和粉",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "neutralize",
    "description": "どんな臭いも打ち消す白い粉。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 30,
    "use": "道具",
    "shopUnlock": null,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_118",
    "name": "光苔のインク",
    "categoryId": "processed",
    "effectId": "mystic",
    "reactionId": "permeate",
    "description": "暗がりでぼんやり光る文字を書けるインク。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 30,
    "use": "道具",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_119",
    "name": "風読みフィオナの軟膏",
    "categoryId": "processed",
    "effectId": "levitation",
    "reactionId": "volatile",
    "description": "塗ると体が羽のように軽くなる軟膏。崖を渡る者の秘薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 360,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_120",
    "name": "賢者アルドラスの霊薬",
    "categoryId": "processed",
    "effectId": "mystic",
    "reactionId": "catalyst",
    "description": "思考が澄み渡り、見落としていた筋道が見えるという霊薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 700,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_121",
    "name": "傷薬の軟膏",
    "categoryId": "processed",
    "effectId": "healing",
    "reactionId": "coagulate",
    "description": "膠と獣脂で練った塗りやすい傷薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 165,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_122",
    "name": "止血粉",
    "categoryId": "processed",
    "effectId": "healing",
    "reactionId": "coagulate",
    "description": "傷口に振りかけて血を止める粉。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 50,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_123",
    "name": "消毒液",
    "categoryId": "processed",
    "effectId": "detox",
    "reactionId": "volatile",
    "description": "傷や器具を清める強い液。染みる。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 205,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_124",
    "name": "解熱の煎じ薬",
    "categoryId": "processed",
    "effectId": "healing",
    "reactionId": "permeate",
    "description": "熱を下げる煎じ薬。冷たいまま飲むとよい。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 155,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_125",
    "name": "強壮酒",
    "categoryId": "processed",
    "effectId": "tonic",
    "reactionId": "permeate",
    "description": "滋養を発酵させて閉じ込めた酒。一杯で足りる。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 175,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_126",
    "name": "覚醒錠",
    "categoryId": "processed",
    "effectId": "stimulation",
    "reactionId": "coagulate",
    "description": "眠気を断つ小さな錠剤。連用は勧められない。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 175,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_127",
    "name": "麻酔液",
    "categoryId": "processed",
    "effectId": "sedation",
    "reactionId": "permeate",
    "description": "痛覚を鈍らせる液。処置の前に用いる。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 205,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "要注意"
  },
  {
    "id": "item_128",
    "name": "防虫香",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "volatile",
    "description": "焚くと虫が寄りつかなくなる香。野営の必需品。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 115,
    "use": "道具",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_129",
    "name": "防寒の膏薬",
    "categoryId": "processed",
    "effectId": "insulation",
    "reactionId": "coagulate",
    "description": "肌に塗って寒さを防ぐ厚い膏薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 250,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_130",
    "name": "虫下し",
    "categoryId": "processed",
    "effectId": "detox",
    "reactionId": "permeate",
    "description": "腹の虫を落とす薬。ひどく苦い。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 75,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_131",
    "name": "洗い粉",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "separate",
    "description": "脂汚れを落とす粉。いわゆる石鹸。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 145,
    "use": "道具",
    "shopUnlock": null,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_132",
    "name": "目薬",
    "categoryId": "processed",
    "effectId": "healing",
    "reactionId": "permeate",
    "description": "目の疲れと濁りを取る澄んだ薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 160,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_133",
    "name": "気付け薬",
    "categoryId": "processed",
    "effectId": "stimulation",
    "reactionId": "volatile",
    "description": "気を失った者の鼻先で栓を抜く刺激薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 265,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_134",
    "name": "携行糧",
    "categoryId": "processed",
    "effectId": "tonic",
    "reactionId": "preserve",
    "description": "日持ちする旅の食糧。味は期待しないこと。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 120,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_135",
    "name": "上級傷薬",
    "categoryId": "processed",
    "effectId": "healing",
    "reactionId": "permeate",
    "description": "深い傷にも届く上等な傷薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 480,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_136",
    "name": "万能解毒丸",
    "categoryId": "processed",
    "effectId": "detox",
    "reactionId": "neutralize",
    "description": "持ち運びやすく固めた解毒の丸薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 300,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_137",
    "name": "深眠薬",
    "categoryId": "processed",
    "effectId": "sedation",
    "reactionId": "volatile",
    "description": "眠れぬ夜を確実に断ち切る薬。翌朝まで覚めない。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 320,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "要注意"
  },
  {
    "id": "item_138",
    "name": "戦士の血止め",
    "categoryId": "processed",
    "effectId": "healing",
    "reactionId": "coagulate",
    "description": "戦場で使う速効の止血薬。酒精で清めながら塞ぐ。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 265,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_139",
    "name": "猛毒の塗り薬",
    "categoryId": "processed",
    "effectId": "poison",
    "reactionId": "coagulate",
    "description": "無臭で刃に留まる猛毒。使えば戻れない。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 450,
    "use": "道具",
    "shopUnlock": null,
    "form": "固形",
    "danger": "凶器"
  },
  {
    "id": "item_140",
    "name": "耐火の護り薬",
    "categoryId": "processed",
    "effectId": "insulation",
    "reactionId": "coagulate",
    "description": "炎熱から身を守る厚い皮膜を作る薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 290,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_141",
    "name": "治癒の秘薬",
    "categoryId": "processed",
    "effectId": "healing",
    "reactionId": "catalyst",
    "description": "超純水で仕立てた治癒の極み。傷が見る間に塞がる。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 590,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_142",
    "name": "霊視の眼薬",
    "categoryId": "processed",
    "effectId": "mystic",
    "reactionId": "permeate",
    "description": "目にさすと見えざるものが映るという眼薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 480,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_143",
    "name": "疾風の丸薬",
    "categoryId": "processed",
    "effectId": "stimulation",
    "reactionId": "volatile",
    "description": "噛み砕くと体が軽く速くなる丸薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 210,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_144",
    "name": "鉄壁の丸薬",
    "categoryId": "processed",
    "effectId": "stable",
    "reactionId": "coagulate",
    "description": "飲めば体が鉛のように重く硬くなる丸薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 220,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_145",
    "name": "魔女レウィシアの秘薬",
    "categoryId": "processed",
    "effectId": "mystic",
    "reactionId": "catalyst",
    "description": "癒しと神秘を一滴に束ねた伝説の秘薬。作れる者はもういない。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 875,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_146",
    "name": "錬金王オルドリンの黄金水",
    "categoryId": "processed",
    "effectId": "stable",
    "reactionId": "catalyst",
    "description": "卑金属を黄金に変えると謳われた水。真偽は誰も知らない。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 660,
    "use": "販売品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_147",
    "name": "死神ヴェルナの一滴",
    "categoryId": "processed",
    "effectId": "poison",
    "reactionId": "catalyst",
    "description": "水と見分けがつかない無色の毒。一滴で足りるという。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 405,
    "use": "販売品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "凶器"
  },
  {
    "id": "item_148",
    "name": "聖女アルテアの祝福水",
    "categoryId": "processed",
    "effectId": "healing",
    "reactionId": "catalyst",
    "description": "傷も病も退けたと伝わる祝福の水。清めの塩が香る。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 640,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_149",
    "name": "隠者ガラハの不老酒",
    "categoryId": "processed",
    "effectId": "tonic",
    "reactionId": "catalyst",
    "description": "百年寝かせたと称される酒。飲んだ者は年を忘れる。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 815,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_150",
    "name": "竜殺しレギンの塗油",
    "categoryId": "processed",
    "effectId": "poison",
    "reactionId": "coagulate",
    "description": "竜の鱗をも侵すという塗油。刃に塗って使う。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 720,
    "use": "道具",
    "shopUnlock": null,
    "form": "固形",
    "danger": "凶器"
  },
  {
    "id": "item_151",
    "name": "星詠みイオラの夢見香",
    "categoryId": "processed",
    "effectId": "mystic",
    "reactionId": "volatile",
    "description": "焚いて眠れば、見た夢が明日を告げるという香。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 595,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_152",
    "name": "万物医アシュレイの万能薬",
    "categoryId": "processed",
    "effectId": "healing",
    "reactionId": "catalyst",
    "description": "あらゆる症状に効くとされる万能薬。医の到達点。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 1020,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_153",
    "name": "城塞守りバルドの不壊薬",
    "categoryId": "processed",
    "effectId": "insulation",
    "reactionId": "coagulate",
    "description": "城門のごとく体を固める護りの薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 500,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_154",
    "name": "鍛冶師ドヴェルの焼き入れ水",
    "categoryId": "processed",
    "effectId": "stable",
    "reactionId": "preserve",
    "description": "刃を鍛えるための水。これで焼き入れた刃は欠けない。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 230,
    "use": "道具",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_155",
    "name": "染料液",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "permeate",
    "description": "布や紙を染めるための液。灰汁で色が定着する。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 60,
    "use": "道具",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_156",
    "name": "墨汁",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "coagulate",
    "description": "骨炭と膠で練った黒い墨。よく伸びる。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 120,
    "use": "道具",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_157",
    "name": "灯火油",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "volatile",
    "description": "煤の少ない灯り用の油。長く燃える。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 80,
    "use": "道具",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_158",
    "name": "煙玉",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "volatile",
    "description": "投げつけると刺激臭の煙が広がる玉。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 115,
    "use": "道具",
    "shopUnlock": null,
    "form": "固形",
    "danger": "要注意"
  },
  {
    "id": "item_159",
    "name": "目つぶし粉",
    "categoryId": "processed",
    "effectId": "stimulation",
    "reactionId": "volatile",
    "description": "顔に撒くと目を開けていられなくなる粉。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 35,
    "use": "道具",
    "shopUnlock": null,
    "form": "粉末",
    "danger": "要注意"
  },
  {
    "id": "item_160",
    "name": "粘着剤",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "coagulate",
    "description": "強く粘る接着剤。乾けば剥がれない。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 105,
    "use": "道具",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_161",
    "name": "防水油",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "preserve",
    "description": "布や革に塗って水を弾かせる油。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 185,
    "use": "道具",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_162",
    "name": "研磨粉",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "separate",
    "description": "刃物や鏡を磨くための細かな粉。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 35,
    "use": "道具",
    "shopUnlock": null,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_163",
    "name": "うがい薬",
    "categoryId": "processed",
    "effectId": "detox",
    "reactionId": "permeate",
    "description": "喉を清める塩気のある薬。朝晩に。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 95,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_164",
    "name": "冷湿布",
    "categoryId": "processed",
    "effectId": "sedation",
    "reactionId": "coagulate",
    "description": "患部を冷やして痛みを和らげる湿布。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 230,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_165",
    "name": "咳止めの煎じ薬",
    "categoryId": "processed",
    "effectId": "sedation",
    "reactionId": "permeate",
    "description": "止まらぬ咳を鎮める煎じ薬。喉に膜を張る。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 150,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_166",
    "name": "発汗薬",
    "categoryId": "processed",
    "effectId": "stimulation",
    "reactionId": "permeate",
    "description": "汗を出させて熱を下げる薬。水を多めに。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 95,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_167",
    "name": "虫刺されの塗り薬",
    "categoryId": "processed",
    "effectId": "detox",
    "reactionId": "coagulate",
    "description": "腫れと痒みを抑える塗り薬。ひんやりする。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 205,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_168",
    "name": "傷口洗浄液",
    "categoryId": "processed",
    "effectId": "detox",
    "reactionId": "volatile",
    "description": "傷を洗うための清潔な液。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 160,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_169",
    "name": "歯磨き粉",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "separate",
    "description": "歯を磨くための粉。塩気と薬草の香り。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 110,
    "use": "道具",
    "shopUnlock": null,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_170",
    "name": "消臭袋",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "preserve",
    "description": "吊しておくと臭いを吸い取る小袋。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 45,
    "use": "道具",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_171",
    "name": "干し肉",
    "categoryId": "processed",
    "effectId": "tonic",
    "reactionId": "preserve",
    "description": "塩を擦り込んで干した肉。旅の友。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 120,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_172",
    "name": "種子の防腐剤",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "separate",
    "description": "種を蒔くまで傷ませないための薬。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 85,
    "use": "道具",
    "shopUnlock": null,
    "form": "液体",
    "danger": "無害"
  },
  {
    "id": "item_173",
    "name": "撒き餌",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "permeate",
    "description": "獣や魚を寄せるための発酵させた餌。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 90,
    "use": "道具",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_174",
    "name": "保冷剤",
    "categoryId": "processed",
    "effectId": "sedation",
    "reactionId": "preserve",
    "description": "冷気を閉じ込めた包み。食料も薬も保つ。",
    "note": "調合でのみ得られる完成品。",
    "source": "調合",
    "price": 140,
    "use": "道具",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_175",
    "name": "薬瓶",
    "categoryId": "relics",
    "effectId": "none",
    "reactionId": "preserve",
    "description": "液体を入れるための小瓶。栓と匙が付いている。",
    "note": "購入品。液体の調合品を作るときに自動で使われる。瓶がなければ、できた薬は流れて消えてしまう。中身を材料として使えば、瓶は棚に戻る。",
    "source": "購入",
    "price": 25,
    "use": "素材",
    "shopUnlock": 0,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_176",
    "name": "弁柄",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "preserve",
    "description": "錆から得た赤い顔料。日に焼けても色が褪せない。",
    "note": "遺物を材料とする調合品。",
    "source": "調合",
    "price": null,
    "use": "道具",
    "shopUnlock": null,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_177",
    "name": "緑青の顔料",
    "categoryId": "processed",
    "effectId": "insulation",
    "reactionId": "preserve",
    "description": "古銭の緑青から得た深い緑の顔料。防腐の力も残る。",
    "note": "遺物を材料とする調合品。",
    "source": "調合",
    "price": null,
    "use": "道具",
    "shopUnlock": null,
    "form": "粉末",
    "danger": "無害"
  },
  {
    "id": "item_178",
    "name": "鉛白",
    "categoryId": "processed",
    "effectId": "poison",
    "reactionId": "coagulate",
    "description": "目の覚めるような白い顔料。美しいが体に障る。",
    "note": "遺物を材料とする調合品。",
    "source": "調合",
    "price": null,
    "use": "道具",
    "shopUnlock": null,
    "form": "粉末",
    "danger": "要注意"
  },
  {
    "id": "item_179",
    "name": "乾燥剤",
    "categoryId": "processed",
    "effectId": "none",
    "reactionId": "separate",
    "description": "湿気を吸い取る焼き締めた粒。薬の保管に。",
    "note": "遺物を材料とする調合品。",
    "source": "調合",
    "price": null,
    "use": "道具",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_180",
    "name": "導きの銅線",
    "categoryId": "processed",
    "effectId": "mystic",
    "reactionId": "catalyst",
    "description": "魔力を端から端まで滞りなく通す銅の線。",
    "note": "遺物を材料とする調合品。",
    "source": "調合",
    "price": null,
    "use": "素材",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_181",
    "name": "遠見の鏡",
    "categoryId": "processed",
    "effectId": "mystic",
    "reactionId": "separate",
    "description": "覗き込むと遠くの景色が映るという鏡。",
    "note": "遺物を材料とする調合品。",
    "source": "調合",
    "price": null,
    "use": "道具",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_182",
    "name": "追想の香",
    "categoryId": "processed",
    "effectId": "sedation",
    "reactionId": "volatile",
    "description": "焚くと忘れていた記憶がふと蘇る香。",
    "note": "遺物を材料とする調合品。",
    "source": "調合",
    "price": null,
    "use": "消耗品",
    "shopUnlock": null,
    "form": "固形",
    "danger": "無害"
  },
  {
    "id": "item_183",
    "name": "ヨイヤミゴケ",
    "categoryId": "fungi",
    "effectId": "mystic",
    "reactionId": "permeate",
    "description": "日の落ちる頃だけ、木漏れ日の跡に薄青く浮かび上がる苔。触れると指先が痺れる。",
    "note": "神秘の素材のうちでは最も見つけやすい。祖母は「宵闇苔」と書いていた。",
    "source": "採取",
    "price": 30,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_184",
    "name": "ホシクズソウ",
    "categoryId": "flora",
    "effectId": "mystic",
    "reactionId": "preserve",
    "description": "高山の草地に混じって生える、白い粒のような花をつける草。夜になると微かに光る。",
    "note": "星屑草。一株ずつしか生えないが、探せばそこそこ見つかる。",
    "source": "採取",
    "price": 30,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_185",
    "name": "ヨナキガイ",
    "categoryId": "creature",
    "effectId": "mystic",
    "reactionId": "catalyst",
    "description": "潮だまりに沈む小さな巻貝。耳に当てると、聞いたことのない音がするという。",
    "note": "夜鳴貝。海辺でしか採れない。祖母はこれを霊銀砂に使っていたらしい。",
    "source": "採取",
    "price": 30,
    "use": "素材",
    "shopUnlock": null,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_186",
    "name": "瀬の走り水",
    "categoryId": "liquid",
    "effectId": "none",
    "reactionId": "neutralize",
    "description": "膝までの浅い流れから汲んだ水。絶えず洗われ続けているため、癖というものを持たない。",
    "note": "岸に寄った浅瀬では、水が石の上をたえず滑っていて澱むということがない。汲めばどこまでも澄んでいて、舌に何も残さない。癖の強い素材どうしがぶつかり合うとき、この水を差せばどちらの角も削れて「中和」する。手に入りやすく、失敗しにくい。最初に覚える水はこれでいい。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_187",
    "name": "水草の絞り水",
    "categoryId": "liquid",
    "effectId": "none",
    "reactionId": "permeate",
    "description": "水面を覆う草を束ねて絞った、青くさい水。薬効を素材の芯まで運ぶ。",
    "note": "根の絡み合った水草を引き上げ、力任せに絞ると、青くさい匂いの水が滴る。草の細い管を通ってきたこの水は、同じように素材の隙間へ入り込んでいく「浸透」の力を持つ。清らかとは言えないが、奥まで届く。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  },
  {
    "id": "item_188",
    "name": "川原の伏流水",
    "categoryId": "liquid",
    "effectId": "none",
    "reactionId": "separate",
    "description": "河原の石を掘ると滲み出す水。砂利を潜るあいだに濁りが置き去りにされている。",
    "note": "水に洗われた石の下には、川とは別の流れが隠れている。掘れば足跡ほどの窪みに水が滲み、しばらく待てば澄んでくる。砂利の層を潜り抜けるあいだに重いものが振り落とされるので、この水は薬液の中でも同じように成分を選り分ける「分離」として働く。",
    "source": "採取",
    "price": 8,
    "use": "素材",
    "shopUnlock": 200,
    "form": "素材",
    "danger": "無害"
  }
];
